name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Étape 1: Vérifiez le code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Étape 2: Configurez Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # Étape 3: Construisez et testez avec Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./simple-api/pom.xml

      # Étape 4: Construisez, testez et analysez avec SonarCloud
      - name: Build, test, and analyze with SonarCloud
        run: |
          cd simple-api
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=Aminorer_Applications_of_Big_Data_lab1 \
            -Dsonar.organization=aminorer \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

            

